import express from 'express';
import cors from 'cors';
import multer from 'multer';
import fs from 'fs';
import path from 'path';
import os from 'os';
import {parse} from 'csv-parse/sync';
import * as XLSX from 'xlsx';
import crypto from 'crypto';

const app=express(); app.use(cors()); app.use(express.json({limit:'2mb'}));
const upload=multer({dest:path.join(os.tmpdir(),'ada-uploads'),limits:{fileSize:25*1024*1024}});
const datasets=new Map(); const reports=new Map();

function isNum(v){return v!==''&&v!==null&&v!==undefined&&!Number.isNaN(Number(v))&&Number.isFinite(Number(v));}
function num(v){return Number(v)}
function mean(a){return a.length?a.reduce((x,y)=>x+y,0)/a.length:0}
function median(a){if(!a.length)return 0;const s=[...a].sort((x,y)=>x-y),m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2}
function std(a){if(a.length<2)return 0;const m=mean(a);return Math.sqrt(mean(a.map(x=>(x-m)**2)))}
function corr(a,b){const n=Math.min(a.length,b.length);if(n<2)return 0;const aa=a.slice(0,n),bb=b.slice(0,n),ma=mean(aa),mb=mean(bb),den=Math.sqrt(aa.reduce((s,x)=>s+(x-ma)**2,0)*bb.reduce((s,x)=>s+(x-mb)**2,0));return den?aa.reduce((s,x,i)=>s+(x-ma)*(bb[i]-mb),0)/den:0}
function parseFile(file){const ext=path.extname(file.originalname).toLowerCase(); if(ext==='.csv'){const text=fs.readFileSync(file.path,'utf8');return parse(text,{columns:true,skip_empty_lines:true,relax_column_count:true});} const wb=XLSX.readFile(file.path);const sheet=wb.Sheets[wb.SheetNames[0]];return XLSX.utils.sheet_to_json(sheet,{defval:null});}
function profile(rows){const cols=[...new Set(rows.flatMap(r=>Object.keys(r)))];const types=cols.map(name=>{const vals=rows.map(r=>r[name]).filter(v=>v!==''&&v!==null&&v!==undefined);const numeric=vals.length&&vals.filter(isNum).length/vals.length>=.85;const date=vals.length&&vals.filter(v=>!Number.isNaN(Date.parse(v))).length/vals.length>=.9&&!numeric;return {name,type:numeric?'numeric':date?'date':'categorical',missing:rows.length-vals.length,unique:new Set(vals.map(String)).size}});const missingCells=types.reduce((s,x)=>s+x.missing,0);const seen=new Set(),dups=[];rows.forEach((r,i)=>{const k=JSON.stringify(r);if(seen.has(k))dups.push(i+1);seen.add(k)});const quality=Math.max(0,Math.round(100-(missingCells/(Math.max(1,rows.length*cols.length))*35)-(dups.length/Math.max(1,rows.length)*25)));return {rows:rows.length,columns:cols.length,missingCells,duplicates:dups.length,qualityScore:quality,types,numeric:types.filter(x=>x.type==='numeric').map(x=>x.name),categorical:types.filter(x=>x.type==='categorical').map(x=>x.name),date:types.filter(x=>x.type==='date').map(x=>x.name)};}
function makeCharts(rows,p){const charts=[];if(p.date.length&&p.numeric.length){const d=p.date[0],n=p.numeric[0],map=new Map();rows.forEach(r=>{const dt=new Date(r[d]);if(Number.isNaN(dt.getTime())||!isNum(r[n]))return;const k=dt.toISOString().slice(0,10);map.set(k,(map.get(k)||0)+num(r[n]));});charts.push({type:'line',title:`${n} over time`,data:[...map.entries()].sort().slice(-30).map(([name,value])=>({name,value:Number(value.toFixed(2))}))});}
 if(p.categorical.length&&p.numeric.length){const c=p.categorical[0],n=p.numeric[0],map=new Map();rows.forEach(r=>{if(!r[c]||!isNum(r[n]))return;map.set(String(r[c]),(map.get(String(r[c]))||0)+num(r[n]));});charts.push({type:'bar',title:`${n} by ${c}`,data:[...map.entries()].sort((a,b)=>b[1]-a[1]).slice(0,10).map(([name,value])=>({name,value:Number(value.toFixed(2))}))});}
 if(!charts.length&&p.numeric.length){const n=p.numeric[0],vals=rows.map(r=>num(r[n])).filter(Number.isFinite);charts.push({type:'bar',title:`Distribution of ${n}`,data:vals.slice(0,20).map((value,i)=>({name:String(i+1),value:Number(value.toFixed(2))}))});}return charts;}
function anomalies(rows,p){const out=[];for(const col of p.numeric){const vals=rows.map(r=>num(r[col])).filter(Number.isFinite),m=mean(vals),s=std(vals);rows.forEach((r,i)=>{if(!isNum(r[col])||!s)return;const z=Math.abs((num(r[col])-m)/s);if(z>=3&&out.length<50)out.push({row:i+1,column:col,value:r[col],score:`z=${z.toFixed(1)}`,reason:'more than 3 standard deviations from the mean'});});}return out;}
function insights(rows,p,charts,anom){const a=[];if(p.rows)a.push(`Analysed ${p.rows.toLocaleString()} rows across ${p.columns} columns with a data-quality score of ${p.qualityScore}/100.`);if(p.numeric.length){const n=p.numeric[0],vals=rows.map(r=>num(r[n])).filter(Number.isFinite);a.push(`${n}: mean ${mean(vals).toFixed(2)}, median ${median(vals).toFixed(2)}, standard deviation ${std(vals).toFixed(2)}.`);}if(p.categorical.length&&p.numeric.length){const c=p.categorical[0],n=p.numeric[0],map=new Map();rows.forEach(r=>{if(r[c]!==undefined&&isNum(r[n]))map.set(String(r[c]),(map.get(String(r[c]))||0)+num(r[n]));});const top=[...map.entries()].sort((x,y)=>y[1]-x[1])[0];if(top)a.push(`${top[0]} has the highest aggregated ${n} among the ${c} categories (${top[1].toFixed(2)}).`);}if(anom.length)a.push(`${anom.length} potential numeric anomalies were detected using a z-score screening rule.`);return a;}
function datasetFrom(file){const rows=parseFile(file);if(!rows.length)throw new Error('The dataset is empty.');const p=profile(rows);const charts=makeCharts(rows,p);const anom=anomalies(rows,p);return {id:crypto.randomUUID(),name:file.originalname,rows,profile:p,charts,anomalies:anom,insights:insights(rows,p,charts,anom),createdAt:new Date().toISOString()};}
function answerQuestion(ds,q){const p=ds.profile,rows=ds.rows,low=q.toLowerCase();let answer='',evidence=[],trace=['Profiled the dataset and identified relevant column types.'];
 if(low.includes('anomal')||low.includes('unusual')){trace.push('Scanned numeric columns for extreme observations.');answer=ds.anomalies.length?`${ds.anomalies.length} potentially unusual observations were detected.`:'No major numeric anomalies were detected by the screening rule.';evidence=ds.anomalies.slice(0,5).map(a=>`${a.column}, row ${a.row}: ${a.value} (${a.reason}).`);}
 else if(p.categorical.length&&p.numeric.length&&(low.includes('highest')||low.includes('top')||low.includes('category'))){const c=p.categorical[0],n=p.numeric[0],map=new Map();rows.forEach(r=>{if(r[c]!==undefined&&isNum(r[n]))map.set(String(r[c]),(map.get(String(r[c]))||0)+num(r[n]));});const top=[...map.entries()].sort((a,b)=>b[1]-a[1]).slice(0,5);trace.push(`Grouped ${n} by ${c}.`);trace.push('Sorted aggregated values and selected the leading categories.');answer=`${top[0]?.[0]||'No category'} has the highest aggregated ${n} at ${top[0]?.[1]?.toFixed(2)||'0'}.`;evidence=top.map(([k,v])=>`${k}: ${v.toFixed(2)}`);}
 else if(p.date.length&&p.numeric.length&&(low.includes('trend')||low.includes('time')||low.includes('changed')||low.includes('declin'))){const c=ds.charts.find(x=>x.type==='line');trace.push(`Aggregated ${p.numeric[0]} by ${p.date[0]}.`);trace.push('Compared the earliest and latest available periods.');const d=c?.data||[];if(d.length>=2){const first=d[0].value,last=d[d.length-1].value,pct=first?((last-first)/first)*100:0;answer=`${p.numeric[0]} changed by ${pct.toFixed(1)}% from the first to the latest displayed period.`;evidence=[`First period: ${d[0].name} = ${first.toFixed(2)}`,`Latest period: ${d[d.length-1].name} = ${last.toFixed(2)}`];}else answer='There is not enough date-based data to establish a trend.';}
 else {trace.push('Calculated descriptive statistics for numeric fields.');if(p.numeric.length){const n=p.numeric[0],v=rows.map(r=>num(r[n])).filter(Number.isFinite);answer=`The strongest starting point is ${n}: mean ${mean(v).toFixed(2)}, median ${median(v).toFixed(2)}, with ${ds.anomalies.filter(a=>a.column===n).length} potential anomalies.`;evidence=[`Mean = ${mean(v).toFixed(2)}`,`Median = ${median(v).toFixed(2)}`,`Standard deviation = ${std(v).toFixed(2)}`];}else answer='This dataset does not contain a numeric field suitable for quantitative analysis.';}
 return {answer,confidence:evidence.length?'High':'Medium',trace,evidence};}
app.post('/api/datasets',upload.single('file'),(req,res)=>{try{if(!req.file)throw new Error('Please upload a CSV or Excel file.');const ds=datasetFrom(req.file);datasets.set(ds.id,ds);fs.unlink(req.file.path,()=>{});const {rows,...safe}=ds;res.json(safe);}catch(e){if(req.file)fs.unlink(req.file.path,()=>{});res.status(400).json({detail:e.message});}});
app.get('/api/datasets/:id',(req,res)=>{const ds=datasets.get(req.params.id);if(!ds)return res.status(404).json({detail:'Dataset not found'});const {rows,...safe}=ds;res.json(safe)});
app.post('/api/analyze',(req,res)=>{const ds=datasets.get(req.body.datasetId);if(!ds)return res.status(404).json({detail:'Dataset not found'});if(!req.body.question)return res.status(400).json({detail:'Question is required'});res.json(answerQuestion(ds,req.body.question));});
app.post('/api/reports/:id',(req,res)=>{const ds=datasets.get(req.params.id);if(!ds)return res.status(404).json({detail:'Dataset not found'});const html=`<!doctype html><html><head><meta charset="utf-8"><title>${ds.name} — AI Report</title><style>body{font-family:Arial;max-width:900px;margin:40px auto;color:#17191d}h1{margin-bottom:5px}.box{border:1px solid #ddd;border-radius:10px;padding:18px;margin:15px 0}li{margin:8px 0}</style></head><body><h1>Autonomous Data Analyst AI</h1><p>${ds.name}</p><div class="box"><h2>Dataset quality</h2><p>Rows: ${ds.profile.rows.toLocaleString()} · Columns: ${ds.profile.columns} · Quality: ${ds.profile.qualityScore}/100 · Missing cells: ${ds.profile.missingCells} · Duplicates: ${ds.profile.duplicates}</p></div><div class="box"><h2>Key insights</h2><ul>${ds.insights.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="box"><h2>Anomalies</h2><ul>${ds.anomalies.slice(0,30).map(x=>`<li>${x.column}, row ${x.row}: ${x.value} — ${x.reason}</li>`).join('')||'<li>None detected</li>'}</ul></div></body></html>`;const id=crypto.randomUUID();reports.set(id,html);res.json({url:`/reports/${id}`});});
app.get('/reports/:id',(req,res)=>{const h=reports.get(req.params.id);if(!h)return res.status(404).send('Report not found');res.type('html').send(h)});
app.get('/api/health',(req,res)=>res.json({ok:true,service:'Autonomous Data Analyst AI'}));
const port=process.env.PORT||8000;app.listen(port,()=>console.log(`Autonomous Data Analyst API running on http://localhost:${port}`));
