import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Upload,Database,BarChart3,Search,AlertTriangle,FileText,Send,Loader2,CheckCircle2,ShieldCheck,Sparkles,Table2,Trash2,RefreshCw} from 'lucide-react';
import {ResponsiveContainer,BarChart,Bar,XAxis,YAxis,Tooltip,CartesianGrid,LineChart,Line,PieChart,Pie,Cell} from 'recharts';
import './styles.css';

const API=import.meta.env.VITE_API_URL||'http://localhost:8000/api';
const demoQuestions=['What are the main trends in this dataset?','Which category has the highest value?','Are there any unusual values or anomalies?','Why might the total have changed over time?'];

function App(){
 const [file,setFile]=useState(null),[dataset,setDataset]=useState(null),[active,setActive]=useState('overview'),[question,setQuestion]=useState(''),[answer,setAnswer]=useState(null),[loading,setLoading]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState('');
 const input=useRef();
 async function upload(f){if(!f)return;setUploading(true);setError('');setAnswer(null);const fd=new FormData();fd.append('file',f);try{const r=await fetch(`${API}/datasets`,{method:'POST',body:fd});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Upload failed');setFile(f);setDataset(d);setActive('overview')}catch(e){setError(e.message)}finally{setUploading(false)}}
 async function ask(q=question){if(!dataset||!q.trim())return;setLoading(true);setError('');setQuestion(q);try{const r=await fetch(`${API}/analyze`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({datasetId:dataset.id,question:q})});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Analysis failed');setAnswer(d);setActive('analyst')}catch(e){setError(e.message)}finally{setLoading(false)}}
 const chart=useMemo(()=>dataset?.charts?.[0],[dataset]);
 return <div className="app">
  <aside className="sidebar"><div className="brand"><div className="brandIcon"><Sparkles size={19}/></div><div><b>Autonomous</b><span>Data Analyst AI</span></div></div>
   <nav>{[['overview',Database,'Overview'],['data',Table2,'Data quality'],['analysis',BarChart3,'Analysis'],['analyst',Search,'AI Analyst'],['anomalies',AlertTriangle,'Anomalies'],['reports',FileText,'Reports']].map(([id,I,label])=><button className={active===id?'active':''} onClick={()=>setActive(id)} key={id}><I size={18}/>{label}</button>)}</nav>
   <div className="sideNote"><ShieldCheck size={17}/><span>Evidence-first analysis. Numerical results come from the dataset, not invented by the AI.</span></div>
  </aside>
  <main className="main"><header><div><div className="eyebrow">AI ANALYTICS WORKSPACE</div><h1>{dataset?dataset.name:'Turn raw data into decisions.'}</h1><p>{dataset?'Your autonomous analysis workspace is ready.':'Upload a CSV or Excel file and let the analyst investigate it.'}</p></div><button className="ghost" onClick={()=>input.current?.click()}><Upload size={17}/> {dataset?'Replace dataset':'Upload dataset'}</button><input ref={input} type="file" accept=".csv,.xlsx,.xls" hidden onChange={e=>upload(e.target.files?.[0])}/></header>
   {error&&<div className="error">{error}</div>}
   {!dataset?<Empty upload={()=>input.current?.click()} uploading={uploading}/>:<>
    <section className="kpis"><Kpi label="Rows" value={dataset.profile.rows.toLocaleString()}/><Kpi label="Columns" value={dataset.profile.columns}/><Kpi label="Quality score" value={`${dataset.profile.qualityScore}%`}/><Kpi label="Anomalies" value={dataset.anomalies.length}/></section>
    <section className="content">
      {active==='overview'&&<Overview dataset={dataset} chart={chart} ask={ask}/>} 
      {active==='data'&&<DataQuality dataset={dataset}/>} 
      {active==='analysis'&&<Analysis dataset={dataset}/>} 
      {active==='analyst'&&<Analyst question={question} setQuestion={setQuestion} ask={ask} answer={answer} loading={loading}/>} 
      {active==='anomalies'&&<Anomalies data={dataset.anomalies}/>} 
      {active==='reports'&&<Reports dataset={dataset}/>} 
    </section>
   </>}
  </main>
 </div>
}
function Kpi({label,value}){return <div className="kpi"><span>{label}</span><strong>{value}</strong></div>}
function Empty({upload,uploading}){return <div className="empty"><div className="uploadBox" onClick={upload}>{uploading?<Loader2 className="spin" size={35}/>:<Upload size={35}/>}<h2>Upload your dataset</h2><p>CSV, XLSX or XLS · up to 25 MB</p><button className="primary">{uploading?'Analysing…':'Choose file'}</button></div><div className="featureGrid">{[['1','Profile','Automatically understand columns, types, missing values and duplicates.'],['2','Investigate','Ask questions in natural language and let the agent plan the analysis.'],['3','Explain','Get evidence-backed findings, anomalies and recommendations.']].map(x=><div className="feature" key={x[0]}><i>{x[0]}</i><div><b>{x[1]}</b><p>{x[2]}</p></div></div>)}</div></div>}
function Overview({dataset,chart,ask}){return <div className="grid2"><div className="card heroCard"><div className="cardHead"><div><span className="label">AUTOMATIC DISCOVERY</span><h2>Dataset intelligence</h2></div><CheckCircle2 size={20}/></div><p className="bigInsight">{dataset.insights[0]||'Your dataset has been profiled and is ready for investigation.'}</p><div className="tags">{dataset.profile.numeric.map(x=><span key={x}># {x}</span>)}</div></div><div className="card"><div className="cardHead"><div><span className="label">ASK THE ANALYST</span><h2>What do you want to know?</h2></div><Search size={20}/></div><div className="questionList">{demoQuestions.map(q=><button onClick={()=>ask(q)} key={q}>{q}<span>→</span></button>)}</div></div><div className="card chartCard"><div className="cardHead"><div><span className="label">VISUAL ANALYSIS</span><h2>{chart?.title||'Distribution'}</h2></div></div><Chart chart={chart}/></div><div className="card"><div className="cardHead"><div><span className="label">QUALITY</span><h2>Data health</h2></div></div><div className="quality"><div className="score">{dataset.profile.qualityScore}<small>/100</small></div><div><b>{dataset.profile.missingCells} missing cells</b><p>{dataset.profile.duplicates} duplicate rows · {dataset.anomalies.length} anomalies</p></div></div></div></div>}
function Chart({chart}){if(!chart)return <div className="emptyChart">No chart available.</div>;if(chart.type==='line')return <ResponsiveContainer width="100%" height={300}><LineChart data={chart.data}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis/><Tooltip/><Line type="monotone" dataKey="value" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer>;return <ResponsiveContainer width="100%" height={300}><BarChart data={chart.data}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="value" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer>}
function DataQuality({dataset}){const p=dataset.profile;return <div className="grid2"><div className="card"><span className="label">DATA QUALITY</span><h2>Profile</h2><div className="qualityRows"><Row k="Rows" v={p.rows.toLocaleString()}/><Row k="Columns" v={p.columns}/><Row k="Missing cells" v={p.missingCells}/><Row k="Duplicate rows" v={p.duplicates}/><Row k="Quality score" v={`${p.qualityScore}/100`}/></div></div><div className="card"><span className="label">SCHEMA</span><h2>Column types</h2><div className="schema">{p.types.map(x=><div key={x.name}><b>{x.name}</b><span>{x.type}</span><em>{x.missing} missing</em></div>)}</div></div></div>}
function Row({k,v}){return <div className="row"><span>{k}</span><b>{v}</b></div>}
function Analysis({dataset}){return <div className="grid2">{dataset.charts.map((c,i)=><div className="card chartCard" key={i}><span className="label">AUTO CHART</span><h2>{c.title}</h2><Chart chart={c}/></div>)}<div className="card"><span className="label">INSIGHTS</span><h2>What the data says</h2><ul className="insights">{dataset.insights.map((x,i)=><li key={i}>{x}</li>)}</ul></div></div>}
function Analyst({question,setQuestion,ask,answer,loading}){return <div className="analyst"><div className="card askCard"><span className="label">AUTONOMOUS INVESTIGATION</span><h2>Ask a business question</h2><p>The agent creates an analysis plan, executes deterministic tools, then explains the verified result.</p><div className="inputRow"><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder="e.g. Why did sales decline?"/><button className="primary" onClick={()=>ask()} disabled={loading}>{loading?<Loader2 className="spin"/>:<Send size={17}/>} Analyze</button></div></div>{loading&&<div className="card"><Loader2 className="spin"/> Running investigation…</div>}{answer&&<div className="resultGrid"><div className="card"><span className="label">ANSWER</span><h2>{answer.answer}</h2><div className="confidence">Confidence: <b>{answer.confidence}</b></div></div><div className="card"><span className="label">INVESTIGATION TRACE</span><h2>What the agent checked</h2><ol className="trace">{answer.trace.map((x,i)=><li key={i}><i>{i+1}</i>{x}</li>)}</ol></div><div className="card"><span className="label">EVIDENCE</span><h2>Supporting data</h2><ul className="insights">{answer.evidence.map((x,i)=><li key={i}>{x}</li>)}</ul></div></div>}</div>}
function Anomalies({data}){return <div className="card"><span className="label">ANOMALY DETECTION</span><h2>Potentially unusual observations</h2>{data.length?<div className="anomalyList">{data.map((a,i)=><div className="anomaly" key={i}><AlertTriangle size={19}/><div><b>{a.column}</b><p>Row {a.row}: value <strong>{a.value}</strong> · {a.reason}</p></div><span>{a.score}</span></div>)}</div>:<div className="success"><CheckCircle2/> No major anomalies detected.</div>}</div>}
function Reports({dataset}){const [busy,setBusy]=useState(false);async function report(){setBusy(true);try{const r=await fetch(`${API}/reports/${dataset.id}`,{method:'POST'});const d=await r.json();if(d.url)window.open(`${API.replace('/api','')}${d.url}`,'_blank')}finally{setBusy(false)}}return <div className="card report"><span className="label">REPORTING</span><h2>Executive analysis report</h2><p>Generate a shareable HTML report containing dataset quality, charts, anomalies and AI investigation results.</p><button className="primary" onClick={report}>{busy?<Loader2 className="spin"/>:<FileText size={17}/>} Generate report</button></div>}
createRoot(document.getElementById('root')).render(<App/>);
